<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run()
    {
        DB::table('products')->insert([
            [
                //living room
                'categoryID' => 1,      //6
                'brandID' => 1,         //10
                'name' => 'Sofa 1',
                'price' => 499.99,
                'quantityInStock' => 20,
                'inStocked' => 20,
                'status' => true,
                'description' => 'A stylish modern sofa.',
                'image' => 'Sofa1_1.jpg',
                'created_at' => '2023-03-01',
                'updated_at' => '2023-03-01',
            ],
            [
                'categoryID' => 1,      //6
                'brandID' => 2,         //10
                'name' => 'Sofa Modern 3',
                'price' => 99.99,
                'quantityInStock' => 200,
                'inStocked' => 200,
                'status' => true,
                'description' => 'A stylish modern sofa.',
                'image' => 'Sofa1_2.jpg',
                'created_at' => '2023-03-01',
                'updated_at' => '2023-03-01',
            ],
            [
                'categoryID' => 1,      //6
                'brandID' => 2,         //10
                'name' => 'Sofa Modern 2',
                'price' => 499.99,
                'quantityInStock' => 12,
                'inStocked' => 12,
                'status' => true,
                'description' => 'A stylish modern sofa 2.',
                'image' => 'Sofa1_3.jpg',
                'created_at' => '2023-03-01',
                'updated_at' => '2023-03-01',
            ],
            [
                'categoryID' => 1,      //6
                'brandID' => 4,         //10
                'name' => 'Sofa Modern 3',
                'price' => 299.99,
                'quantityInStock' => 11,
                'inStocked' => 11,
                'status' => true,
                'description' => 'A stylish modern sofa 3.',
                'image' => 'Sofa1_4.jpg',
                'created_at' => '2023-03-01',
                'updated_at' => '2023-03-01',
            ],
            [
                'categoryID' => 1,      //6
                'brandID' => 5,         //10
                'name' => 'Sofa Modern 4',
                'price' => 999.99,
                'quantityInStock' => 3,
                'inStocked' => 3,
                'status' => true,
                'description' => 'A stylish modern sofa 4.',
                'image' => 'Sofa1_5.jpg',
                'created_at' => '2023-12-01',
                'updated_at' => '2023-12-01',
            ],
            [
                'categoryID' => 1,      //6
                'brandID' => 6,         //10
                'name' => 'Sofa Modern 5',
                'price' => 899.99,
                'quantityInStock' => 6,
                'inStocked' => 6,
                'status' => true,
                'description' => 'A stylish modern sofa 5.',
                'image' => 'Sofa2_1.jpg',
                'created_at' => '2023-12-01',
                'updated_at' => '2023-12-01',
            ],
            // bebroom
            [
                'categoryID' => 2,      //6
                'brandID' => 9,         //10
                'name' => 'Bed Room 1',
                'price' => 899.99,
                'quantityInStock' => 6,
                'inStocked' => 6,
                'status' => true,
                'description' => 'bed room.',
                'image' => 'bed1_1.jpg',
                'created_at' => '2023-12-01',
                'updated_at' => '2023-12-01',
            ],
            [
                'categoryID' => 2,      //6
                'brandID' => 10,         //10
                'name' => 'Bed Room 2',
                'price' => 900.9,
                'quantityInStock' => 60,
                'inStocked' => 60,
                'status' => true,
                'description' => 'bed room.',
                'image' => 'bed1_2.jpg',
                'created_at' => '2023-11-01',
                'updated_at' => '2023-11-01',
            ],
            [
                'categoryID' => 2,      //6
                'brandID' => 6,         //10
                'name' => 'Bed Room 3',
                'price' => 889.91,
                'quantityInStock' => 32,
                'inStocked' => 32,
                'status' => true,
                'description' => 'bed room.',
                'image' => 'bed1_3.jpg',
                'created_at' => '2023-11-01',
                'updated_at' => '2023-11-01',
            ],
            [
                'categoryID' => 2,      //6
                'brandID' => 7,         //10
                'name' => 'Bed Room 4',
                'price' => 549.09,
                'quantityInStock' => 230,
                'inStocked' => 230,
                'status' => true,
                'description' => 'bed room.',
                'image' => 'bed1_4.jpg',
                'created_at' => '2023-11-01',
                'updated_at' => '2023-11-01',
            ],
            [
                'categoryID' => 2,      //6
                'brandID' => 8,         //10
                'name' => 'Bed Room 5',
                'price' => 849.59,
                'quantityInStock' => 234,
                'inStocked' => 234,
                'status' => true,
                'description' => 'bed room.',
                'image' => 'bed2_1.jpg',
                'created_at' => '2023-07-01',
                'updated_at' => '2023-07-01',
            ],
            // dinner
            [
                'categoryID' => 3,
                'brandID' => 1,
                'name' => 'Wooden Dining Table 1',
                'price' => 2199.99,
                'quantityInStock' => 52,
                'inStocked' => 52,
                'status' => true,
                'description' => 'Elegant wooden dining table for 6.',
                'image' => 'dining_table1.jpg',
                'created_at' => '2023-07-01',
                'updated_at' => '2023-07-01',
            ],
            [
                'categoryID' => 3,
                'brandID' => 2,
                'name' => 'Wooden Dining Table 2',
                'price' => 29.99,
                'quantityInStock' => 135,
                'inStocked' => 135,
                'status' => true,
                'description' => 'Elegant wooden dining table for 63.',
                'image' => 'dining_table2.jpg',
                'created_at' => '2023-07-01',
                'updated_at' => '2023-07-01',
            ],
            [
                'categoryID' => 3,
                'brandID' => 5,
                'name' => 'Wooden Dining Table 3',
                'price' => 269.49,
                'quantityInStock' => 42,
                'inStocked' => 42,
                'status' => true,
                'description' => 'Elegant wooden dining table for 32.',
                'image' => 'dining_table3.jpg',
                'created_at' => '2024-03-01',
                'updated_at' => '2024-03-01',
            ],
            [
                'categoryID' => 3,
                'brandID' => 6,
                'name' => 'Wooden Dining Table 4',
                'price' => 245.99,
                'quantityInStock' => 260,
                'inStocked' => 260,
                'status' => true,
                'description' => 'Elegant wooden dining table for 245.',
                'image' => 'dining_table4.jpg',
                'created_at' => '2024-03-01',
                'updated_at' => '2024-03-01',
            ],
            [
                'categoryID' => 3,
                'brandID' => 8,
                'name' => 'Wooden Dining Table 5',
                'price' => 39.99,
                'quantityInStock' => 61,
                'inStocked' => 61,
                'status' => true,
                'description' => 'Elegant wooden dining table for 634.',
                'image' => 'dining_table5.jpg',
                'created_at' => '2024-03-01',
                'updated_at' => '2024-03-01',
            ],
            //bathroom
            [
                'categoryID' => 4,
                'brandID' => 1,
                'name' => 'Bathroom',
                'price' => 49.99,
                'quantityInStock' => 10,
                'inStocked' => 10,
                'status' => true,
                'description' => 'for your collection.',
                'image' => 'bathroom1.jpg',
                'created_at' => '2024-05-01',
                'updated_at' => '2024-05-01',
            ],
            [
                'categoryID' => 4,
                'brandID' => 2,
                'name' => 'Bathroom 2',
                'price' => 4.99,
                'quantityInStock' => 20,
                'inStocked' => 20,
                'status' => true,
                'description' => 'for your collection.',
                'image' => 'bathroom2.jpg',
                'created_at' => '2024-05-01',
                'updated_at' => '2024-05-01',
            ],
            [
                'categoryID' => 4,
                'brandID' => 3,
                'name' => 'Bathroom 3',
                'price' => 6.99,
                'quantityInStock' => 22,
                'inStocked' => 22,
                'status' => true,
                'description' => 'for your collection.',
                'image' => 'bathroom3.jpg',
                'created_at' => '2024-05-01',
                'updated_at' => '2024-05-01',
            ],
            [
                'categoryID' => 4,
                'brandID' => 4,
                'name' => 'Bathroom 4',
                'price' => 9.99,
                'quantityInStock' => 11,
                'inStocked' => 11,
                'status' => true,
                'description' => 'for your collection.',
                'image' => 'bathroom4.jpg',
                'created_at' => '2024-07-01',
                'updated_at' => '2024-07-01',
            ],
            [
                'categoryID' => 4,
                'brandID' => 5,
                'name' => 'Bathroom 5',
                'price' => 49.9,
                'quantityInStock' => 34,
                'inStocked' => 34,
                'status' => true,
                'description' => 'for your collection.',
                'image' => 'bathroom5.jpg',
                'created_at' => '2024-07-01',
                'updated_at' => '2024-07-01',
            ],

            // chair
            [
                'categoryID' => 5,
                'brandID' => 1,
                'name' => 'Office Chair',
                'price' => 199.99,
                'quantityInStock' => 81,
                'inStocked' => 81,
                'status' => true,
                'description' => 'Comfortable accent chair for any room.',
                'image' => 'chair1_1.jpg',
                'created_at' => '2024-07-01',
                'updated_at' => '2024-07-01',
            ],
            [
                'categoryID' => 5,
                'brandID' => 2,
                'name' => 'Office Chair 2',
                'price' => 199.00,
                'quantityInStock' => 320,
                'inStocked' => 320,
                'status' => true,
                'description' => 'Comfortable accent chair for any room.',
                'image' => 'chair1_2.jpg',
                'created_at' => '2024-07-01',
                'updated_at' => '2024-07-01',
            ],
            [
                'categoryID' => 5,
                'brandID' => 3,
                'name' => 'Office Chair 3',
                'price' => 139.01,
                'quantityInStock' => 120,
                'inStocked' => 120,
                'status' => true,
                'description' => 'Comfortable accent chair for any room.',
                'image' => 'chair1_3.jpg',
                'created_at' => '2024-07-01',
                'updated_at' => '2024-07-01',
            ],
            [
                'categoryID' => 5,
                'brandID' => 4,
                'name' => 'Office Chair 4',
                'price' => 444.99,
                'quantityInStock' => 444,
                'inStocked' => 444,
                'status' => true,
                'description' => 'Comfortable accent chair for any room 444.',
                'image' => 'chair1_4.jpg',
                'created_at' => '2024-08-01',
                'updated_at' => '2024-08-01',
            ],
            [
                'categoryID' => 5,
                'brandID' => 5,
                'name' => 'Office Chair 5',
                'price' => 91.99,
                'quantityInStock' => 333,
                'inStocked' => 333,
                'status' => true,
                'description' => 'Comfortable accent chair for any room.',
                'image' => 'chair1_5.jpg',
                'created_at' => '2024-08-01',
                'updated_at' => '2024-08-01',
            ],
            [
                'categoryID' => 5,
                'brandID' => 6,
                'name' => 'Office Chair 6',
                'price' => 901.99,
                'quantityInStock' => 20,
                'inStocked' => 20,
                'status' => true,
                'description' => 'Comfortable accent chair for any room.',
                'image' => 'chair2_1.jpg',
                'created_at' => '2024-08-01',
                'updated_at' => '2024-08-01',
            ],
            [
                'categoryID' => 5,
                'brandID' => 7,
                'name' => 'Office Chair 7',
                'price' => 1.99,
                'quantityInStock' => 66,
                'inStocked' => 66,
                'status' => true,
                'description' => 'Comfortable accent chair for any room.',
                'image' => 'chair2_2.jpg',
                'created_at' => '2024-08-01',
                'updated_at' => '2024-08-01',
            ],
            [
                'categoryID' => 5,
                'brandID' => 8,
                'name' => 'Office Chair 8',
                'price' => 9.99,
                'quantityInStock' => 201,
                'inStocked' => 201,
                'status' => true,
                'description' => 'Comfortable accent chair for any room.',
                'image' => 'chair2_3.jpg',
                'created_at' => '2024-08-01',
                'updated_at' => '2024-08-01',
            ],
            [
                'categoryID' => 5,
                'brandID' => 9,
                'name' => 'Office Chair 9',
                'price' => 9.99,
                'quantityInStock' => 207,
                'inStocked' => 207,
                'status' => true,
                'description' => 'Comfortable accent chair for any room.',
                'image' => 'chair2_4.jpg',
                'created_at' => '2024-09-01',
                'updated_at' => '2024-09-01',
            ],
            [
                'categoryID' => 5,
                'brandID' => 10,
                'name' => 'Office Chair 10',
                'price' => 11.99,
                'quantityInStock' => 920,
                'inStocked' => 920,
                'status' => true,
                'description' => 'Comfortable accent chair for any room.',
                'image' => '',
                'created_at' => '2024-09-01',
                'updated_at' => '2024-09-01',
            ],
        ]);
    }
}
